clean2:
	-$(RM) $(CC_DEPS)$(C++_DEPS)$(C_UPPER_DEPS)$(CXX_DEPS)$(SECONDARY_FLASH)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_UPPER_DEPS)$(C_DEPS)$(CPP_DEPS)
	-$(RM) $(OBJS) *.elf
	-@echo ' '
    
*.elf: $(wildcard ..C:/Users/ALanStewart/Documents/Project-L431RCT6-EVB/Software/RT_Thread_example/1-Temp_Project/linkscripts/STM32L431RCTx/link.lds)
